name: Feature branch

on:
  workflow_dispatch:
  pull_request:
  push:
    branches-ignore:
      - main

env:
  NODE_VERSION: '20'

jobs:
  code-check:
    name: Code checking
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      # Main logic
      - name: Install dependencies
        run: npm install

      - name: Code checking
        run: |
          npm run lint
